version: '3.8'

services:
  nodeapp:
    image: dockertutapp
    container_name: samplewala
    environment:
      - PORT=4000
      # Uncomment and set your MongoDB URI if needed
      - MONGO_URI=mongodb://admin:password@mongodb
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: dockertutDB
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  authservice:
    image: auth
    ports:
      - "5000:5000"
    depends_on:
      - nodeapp
    environment:
      - PORT=5000

  nextjsservice:
    image: nextjs 
    ports:
      - "3000:3000"
    depends_on:
      - nodeapp
      - mongodb
      - authservice
 
